### ISSUE TITLE
This crate is awesome but example needs to be improved

### ISSUE THREAD

**Issue by williamdes** [marcelbuesing/bme680#41]
This crate is awesome but without a bit more for the example it can be difficult to try  it simply

The i2cdetect command on the README is very helpful !

For example I was running `cargo run --release` and did not see any output but it needed `RUST_LOG=info cargo run --release`

Cargo dependencies should be written in a Cargo.toml file for example so you do not have to pick them one by one until it compiles

```toml
[dependencies]
bme680 = "0.6.0"
embedded-hal = "0.2.6"
linux-embedded-hal = "0.3.0"
log = "0.4.14"
env_logger = "0.9.0"
```

Conclusion: with dependencies and `RUST_LOG=info` it works !

**THANK YOU for saving me from the Python HELL !**
